import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Menu } from "lucide-react";
import {
  Sheet,
  SheetContent,
  SheetTrigger,
  SheetTitle,
} from "@/components/ui/sheet";
import  Footer  from "../componentsPage/Footer";

const be_Vietnam_Pro = Be_Vietnam_Pro({
  variable: "--font-bvp-sans",
  weight: ["300", "400","500","600","700","900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${be_Vietnam_Pro.className} min-h-screen flex flex-col`}
      >
        <header className="border-b sticky top-0 bg-background z-50">
          <nav className="container mx-auto px-4 py-4">
            <div className="flex justify-between items-center">
              <Link href="/" className="text-xl font-bold">
                PORTAL DOSEN
              </Link>

              {/* Desktop Navigation */}
              <div className="hidden md:flex gap-4">
                <Button variant="ghost" asChild>
                  <Link href="/materials">Materials</Link>
                </Button>
                <Button variant="ghost" asChild>
                  <Link href="/publications">Publications</Link>
                </Button>
                <Button variant="ghost" asChild>
                  <Link href="/schedule">Schedule</Link>
                </Button>
                <Button variant="ghost" asChild>
                  <Link href="/about">About</Link>
                </Button>
              </div>

              {/* Mobile Navigation */}
              <Sheet>
                <SheetTrigger className="md:hidden">
                  <Menu className="w-6 h-6" />
                </SheetTrigger>
                <SheetContent>
                  <SheetTitle>Navigation Menu</SheetTitle>
                  <div className="flex flex-col gap-4 mt-8">
                    <Link href="/materials" className="text-lg">
                      Materials
                    </Link>
                    <Link href="/publications" className="text-lg">
                      Publications
                    </Link>
                    <Link href="/schedule" className="text-lg">
                      Schedule
                    </Link>
                    <Link href="/about" className="text-lg">
                      About
                    </Link>
                  </div>
                </SheetContent>
              </Sheet>
            </div>
          </nav>
        </header>
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
//  className={`${be_Vietnam_Pro.variable} antialiased`}